name: Release Zed extension

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to publish (for example, 0.0.6)
        required: true
        type: string

permissions:
  contents: read

jobs:
  bump-zed-extension:
    name: Bump Zed extension
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v2
        with:
          extension-name: crystal
          push-to: crystal-lang-tools/zed-extensions
          tag: ${{ inputs.tag || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
